# .travis.yml 文件

# 声明构建语言环境
language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-26
    - android-29
script:
  # 生成 APK
  - ./gradlew assembleRelease

# 部署
deploy:
  # 部署到GitHub Release。
  provider: releases
  # Github oauth token
  api_key: ${TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/release/app-release-unsigned.apk
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  # 发布时机
  on:
    branch: master