# 声明构建语言环境
language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    # 构建项目所用的BuildTools版本
    - build-tools-29.0.3
    # 用来编译项目的SDK版本
    - android-29

before_script:
  - chmod +x gradlew

# 运行脚本
script:
  # 生成release apk包
  - ./gradlew assembleRelease

# 部署
deploy:
  # 部署到GitHub Release
  provider: releases
  # Github oauth token
  api_key: ${TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: app/build/outputs/apk/release/app-release-unsigned.apk
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  # 发布时机
  on:
    branch: master